name: Test
on: [push]
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  test:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v2
        with:
          python-version: 3.14
      - run: |
          make test
          source .venv/bin/activate && oj-verify docs
      - uses: actions/jekyll-build-pages@v1
        with:
          source: .verify-helper/markdown
          destination: _site
      - uses: actions/configure-pages@v4
      - uses: actions/upload-pages-artifact@v3
        with:
          path: _site
      - id: deployment
        uses: actions/deploy-pages@v4
